### ISSUE TITLE
Unable to Delete Row

### ISSUE THREAD

**Issue by ccrawford93** [salesforce-marketingcloud/FuelSDK-Java#12]
I am currently running on revision 665107845a84be24c5fefd128ad88d2cc80a03b8. If any of this will be fixed in an upcoming release, please let me know.

As of now, I have no way to delete a row in any data extension. Here is my code:

``` java
String deName = "Test DE";
        ETFilter deFilter = new ETSimpleFilter("Name", ETFilterOperators.EQUALS, deName);

        ETDataExtension dataExtension;
        try {
            dataExtension = client.retrieveDataExtension(deFilter);
        } catch (ETSdkException e) {
            throw new Exception(String.format("There was no matching data extension with the provided name. Name: %s", deName));
        }

        ETFilter rowFilter = new ETSimpleFilter("Email Address", ETFilterOperators.EQUALS, "clientTest@gmail.com");

List<ETResult> results;
        try {
            results = dataExtension.delete(rowFilter);
        } catch (ETSdkException e) {
            throw new Exception(String.format("There was an error deleting the row for the data extension. ExtensionName: %s", deName), e);
        }
```

These calls result in an error code of 310007 and a message of "Keys Not Found". I have also tried utilizing the deprecated service, in addition to trying to use the deprecated setter for "Keys" but have had no success:

``` java
// Deprecated stuff fails as well
        List<ETDataExtensionRow> rowList = dataExtension.select(rowFilter);
        Map<String, String> blah = new HashMap<String, String>();
        blah.put("Email Address", "clientTest@gmail.com");
        rowList.get(0).setKeys(blah);
        ETResponse<ETResult> response;
        try {
            rowList.get(0).setName(deName);
            response = dataExtensionRowService.delete(client, rowList.get(0));
        } catch (ETSdkException e){
            throw new Exception(String.format("There was error deleting the row for the data extension. ExtensionName: %s", deName));
        }
```

Furthermore, I have found a related issue in the ruby sdk that could potentially be related given the "properties/property" vs "keys/key". http://salesforce.stackexchange.com/questions/33398/fuel-sdk-ruby-client-delete-a-row-from-a-data-extension

Is this an issue of needing to be refactored, not using the calls in the correct manner, or not using the most recent version of the sdk (which is broken, see other issue I've created). Any information would be helpful.

PS: To be clear, all of the objects and their names are correct and return the corresponding object back to my client. I have traced the issue directly until the point in which the SOAP call is made.

**Comment by matrostik** [comment]
Wow the issue still exits
