### ISSUE TITLE
Unable to retrieve ETTriggeredEmails

### ISSUE THREAD

**Issue by algra** [salesforce-marketingcloud/FuelSDK-Java#84]
Hi there,

I'm trying to retrieve list of triggered send definitions, as far as I understood from documentation, ETTriggeredEmail is the class in the SDK which corresponds to triggered send definitions.

Here is piece of Scala code:

```scala
  val config = new ETConfiguration()
  config.set("username", "my-username")
  config.set("password", "my-password")
  config.set("soapEndpoint", "https://webservice.s7.exacttarget.com/Service.asmx")

  val client = new ETClient(config)

  val response = client.retrieve(classOf[ETTriggeredEmail])

  Console.println(response)
```

so, no sophisticated logic at all, to me it looks like "get list of all triggered send definitions". When I run it, i get:

```
com.exacttarget.fuelsdk.ETResponse[
    batchResult = com.exacttarget.fuelsdk.ETResult[
        requestId = c01dff21-95ab-4459-ac75-c315c0634170
        responseCode = Error: The Request Property(s) SendClassification do not match with the fields of TriggeredSendDefinition retrieve
        responseMessage = Error: The Request Property(s) SendClassification do not match with the fields of TriggeredSendDefinition retrieve
    ]
    individualResults = []
    moreResults = false
]
```

So, somehow doing a quite basic operation is broken here.

Any help would be appreciated, thanks!

**Comment by sharif26** [comment]
Please check our sample test code [here](https://github.com/salesforce-marketingcloud/FuelSDK-Java/blob/master/src/test/java/com/exacttarget/fuelsdk/ETTriggeredTest.java#L54)
The main idea is to use filter to avoid SendClassification which is retrieved by default.
